services:
  - type: web
    name: inner
    env: node
    plan: free
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: HOST
        value: "0.0.0.0"
      - key: NODE_ENV
        value: "production"
